apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuinn-bot
spec:
  selector: 
    matchLabels:
      app: cuinn-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: cuinn-bot
    spec:
      containers:
      - image: quay.io/kennedn/cuinn-bot:latest
        name: cuinn-bot
        envFrom:
        - configMapRef:
            name: cuinn-bot-env
